---
- name: Configure firewalld ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 6443/tcp

- name: Configure firewalld, vrrp
  firewalld:
    rich_rule: rule protocol value="vrrp" accept
    permanent: yes
    state: enabled

- name: Reload firewalld
  command: >
    firewall-cmd --reload
    
- name: Install nginx, keepalived packages
  yum: 
    name: 
      - nginx
      - keepalived
    state: present

- name: Copy the nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Restart nginx
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: Copy the keepalived configuration file
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Restart keepalived
  service:
    name: keepalived
    enabled: yes
    state: restarted

- name: Copy cnt8-00-sysctl.conf to /etc/sysctl.d/00-sysctl.conf
  copy:
    src: sysctl.d/cnt8-00-sysctl.conf
    dest: /etc/sysctl.d/00-sysctl.conf
 
- name: Reload sysctl variables
  command: >
    sysctl -p /etc/sysctl.d/00-sysctl.conf