---
# ==================================
# system config
# ==================================
- name: Configure firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 179/tcp
    - 10250/tcp
    - 10255/tcp
    - 30000-32767/tcp
    - 6783/tcp

- name: Reload firewalld
  command: >
    firewall-cmd --reload

- name: Get worker join command
  delegate_to: "{{ groups.masters[0] }}"
  command: >
    kubeadm token create --print-join-command
  register: add_worker_to_cluster_cmd
  run_once: yes

- name: Join worker node
  command: "{{ add_worker_to_cluster_cmd.stdout }}"
